### ISSUE TITLE
マインクラフトのコマンドからOSのコマンドを実行する

### ISSUE THREAD

**Issue by jetyum** [koshianpan/Popopo#1]
## 動機
毎回sshにログインするのがめんどくさくなった. 一部のみを操作する方法を模索していたが設定ファイルなどは変わり得るのでいっそのことマインクラフトの中からOSのコマンドを実行できてしまえば楽になるのではないかと考えた.

**Comment by koshianpan** [comment]
## 課題
* まず同期では不可能
* 複数回にわたって入力する場合がある
* 結果はすぐには帰ってこない
* cdコマンドなど一部のコマンドが使えない
* コマンドを停止させるすべがない
* 現行のMessengerでは表示が見にくい

**Comment by jetyum** [comment]
## 概要
実装しました. 要素は以下のとおりです. 
* sudoコマンドは使用不可能(入力文字列の中に含まれるか調べているだけ)
* 非同期処理
* 使えないコマンドも多く存在します
* プラグイン終了時には強制的に全プロセスが終了します
