### ISSUE TITLE
コマンドの実装を簡単に行えるようなフレームワークを作る

### ISSUE THREAD

**Issue by jetyum** [koshianpan/Popopo#3]
## 動機
コマンドが増えると補完の処理を書いたりすることが煩雑になるので他の複雑な機能が実装される前に整備しておく.

**Comment by koshianpan** [comment]
## 概要
あれば問題ない部分は実装完了しました. 一応使い方を以下に示します. 

## 使用方法
コマンドの定義はDefinitionをimplementsしたクラス内で行います. 例を示します. 
``` java
public class SampleCommand implements Definition {
    @Override
    public String getCommand() {
        return "sample";
    }

    @Executor({"add", "player"})
    public boolean onAddCommand(Map<String, String> args) {
        // do something
        return true;
    }

    @Executor({"remove", "player"})
    public boolean onRemoveCommand(Map<String, String> args) {
        // do something
        return true;
    }
}
```
このように定義します. Executorの引数の最初の要素でサブコマンドを指定します. スペースを用いても構いません. それ以降の要素は引数の種類を表すもので引数のMapのkeyになります. 複数設定可能です. Main文に次を追加してplugin.ymlに記述を行えば使えるようになります. 
``` java
Factory f = new Factory();

f.create(new SampleCommand()).setTo(this);
```
Executorに設定する引数の種類を示す単語には意味がありTabキーによりコマンドを補完するときに使われます. デフォルトではプレイヤー名を示すplayer, ワールド名を示すworld, ワールドの環境名を示すenvironment, マテリアル名を示すmaterialが定義されています. 補完機能は今後の状態によって仕様が変わる可能性があります.

**Comment by jetyum** [comment]
## 注意

### この仕様は古い仕様です. 現在の新しい仕様は下のコメントを参照してください.

## 概要
あれば問題ない部分は実装完了しました. 一応使い方を以下に示します. 

## 使用方法
コマンドの定義は`Definition`をimplementsしたクラス内で行います. 例を示します. 
``` java
public class SampleCommand implements Definition {
    @Override
    public String getCommand() {
        return "sample";
    }

    @Executor({"add", "player"})
    public boolean onAddCommand(Caster c, Argument arg) {
        // do something
        return true;
    }

    @Executor({"remove", "player"})
    public boolean onRemoveCommand(Caster c, Argumrnt arg) {
        // do something
        return true;
    }
}
```
このように定義します. `@Executor`の引数の最初の要素でサブコマンドを指定します. スペースを用いても構いません. それ以降の要素は引数の種類を表すもので`Argument`のkeyになります. 複数設定可能です. Main文に次を追加して`plugin.yml`に記述を行えば使えるようになります. 
``` java
Factory f = new Factory();

f.create(new SampleCommand(), theme).setTo(this);
```
`@Executor`に設定する引数の種類を示す単語には意味がありTabキーによりコマンドを補完するときに使われます. デフォルトではプレイヤー名を示す`player`, ワールド名を示す`world`, ワールドの環境名を示す`environment`, マテリアル名を示す`material`が定義されています. 補完機能は今後の状態によって仕様が変わる可能性があります. 
## 未実装
次の機能は実装されていません. 
* 自分で実装した`Completer`を追加してオリジナルの補完を行う.

**Comment by jetyum** [comment]
## 使用方法
コマンドの定義は`Command`をimplementsしたクラス内で行います. 例を示します. 
``` java
public class SampleCommand implements Command {
    @SubCommand(name = "add")
    public void onAddCommand(Caster c, Player p) {
        // do something
    }

    @SubCommand(name = "remove")
    public void onRemoveCommand(Caster c, Player p) {
        // do something
    }

    @NameGetter(Player.class)
    public Set<String> getPlayerNames() {
        // returning player names
    }

    @ValueGetter(Player.class)
    public Player getPlayer(Caster c, String arg) {
        // getting instance of player class
    }
}
```
このように定義します. `@SubCommand`の引数はサブコマンドの名前となります. 複数設定しても構いません. このアノテーションを付与したメソッドの入力引数の`Caster`以降がそのままコマンドの入力引数に設定されます. ここに`String`以外を使用する場合は必ずこれとは別にサンプルに示したような`@ValueGetter`を付与したメソッドを用意する必要があります. 補完を使用する場合は`@NameGetter`を付与したメソッドを用意してください. 
> **Note**
> アノテーションを付与するメソッドの引数と戻り値は次のように定義しなければ期待する動作を保証できません. 
> `@SubCommand`  始めに`Caster`で以降は任意に定義する. 戻り値はなし. 
> `@NameGetter`  引数は取らず, 戻り値は`Set<String>`と定義する. 
> `@ValueGetter`  引数は`Caster`, `String`の順に定義する. 戻り値は任意. 

ここで定義したコマンドはMain文に次を追加することで`plugin.yml`に設定済みならばすぐに使用できます. 
``` java
CmdManager m = new CmdManager(plugin, formatter);

m.register("sample", new SampleCommand());
```
