### ISSUE TITLE
サーバーを再起動しても保持される情報の管理を簡略化する

### ISSUE THREAD

**Issue by jetyum** [koshianpan/Popopo#4]
## 動機
保存の必要なデータは単純なymlファイルに収まるものばかりではないのでserializeで管理を行う. コマンドの機能にも重要になる部分があるのでコマンド系の整備と同時に実装を行いたい.

**Comment by koshianpan** [comment]
## 概要
簡易化された設定機能を実装したので使用方法を示す. 
## 使用方法
設定は`Config`クラスとYamlで書かれた設定ファイルを用いて適用します. 静的でありサーバー実行中にコマンドによって変更されることは考えられていません. `Config`で設定を行う対象にしたいクラスは`Congifurable`をimplementする必要があります. 以下に示すYamlファイルを使う例を考えます. 
``` yml
sample:
  text: hello!
  chat_color: yellow
  num: 10
  list:
    - a
    - b
    - c
```
これらの値を設定する対象となるクラスの例を示します. 
``` java
public class Sample implements Configurable {
    @Parameter("text")
    private String text = "";

    @Parameter("chat_color")
    private CharColor chatColor = ChatColot.WHITE;

    @Parameter("num")
    private int num = 0;

    @Parameter("list")
    List<String> list = new ArrayList<>();

    @Override
    public String getConfigName() {
        return "sample";
    }
}
```
このようにして設定するパラメータに`@Parameter`を付与することで設定するフィールドであることを明示します. `@Parameter`の引数はYamlファイルの中での各パラメータのラベルになります. そして`getConfigName`で指定された文字列がYaml内でこの設定項目を指すラベルになります. データ型は基本的なものに加えて列挙型をYamlファイル中の文字列から設定できます. 項目を注入する際は次のようにします. 
``` java
Config config = new Config();
Sample sample = new Sample();

if (config.load("config.yml")) {
    config.setTo(sample);
}
```
この操作によりパラメータがYamlファイル内に記述されたものに設定されます.

**Comment by jetyum** [comment]
## 注意

### この仕様は古い仕様です. 現在の新しい仕様は下のコメントを参照してください.

## 概要
簡易化された設定機能を実装したので使用方法を示す. 
## 使用方法
設定を行う対象にしたいクラスは`Configurable`をimplementsしておきます. そして操作を行う対象のフィールドに`@Parameter`を付与します. 引数は設定項目のキーになります. 使用例を以下に示します. 
``` java
public class Sample implements Configurable {
    @Parameter("num")
    private int num = 10;

    @Parameter("text")
    private String text = "hello!";

    @Override
    public String getSectionName() {
        return "sample";
    }
}
```
上の例にはありませんが, `@Parameter`に列挙型を指定した場合は文字列に変換されて保存されます. 読み込み時に再び列挙型に変換されますが大文字小文字は区別されません. 他にも`Map`や`List`なども使用できます. このクラスの初期値と等価な内容を表すYamlファイルを示しておきます. 
``` yml
sample:
  num: 10
  text: hello!
```
Yamlファイルから設定を行う場合には`YamlConfig`を, 設定ファイルを圧縮してしまっておく場合には`GzipConfig`を使用します. `Configurable`をimplementsしたクラスに設定を行う例を示しておきます. 
``` java
Sample sample = new Sample();
YamlConfig yml = YamlConfig.newFrom(this, path);

// on start
yml.injectInto(sample);

// on finish
yml.extractFrom(sample);
yml.save();
```
`YamlConfig`の場合は`newFrom`の引数`path`を省略することで`config.yml`を対象にします.

**Comment by jetyum** [comment]
## 使用方法
操作を行う対象のフィールドに`@Property`を付与します. 引数は設定項目のキーになります. 使用例を以下に示します. 
``` java
public class Sample {
    @Property(key = "num")
    private int num = 10;

    @Property(key = "text")
    private String text = "hello!";
}
```
上の例にはありませんが, 列挙型を指定した場合は文字列に変換されて保存されます. 読み込み時に再び列挙型に変換されますが大文字小文字は区別されません. 他にも`Map`や`List`なども使用できます. (`YamlConfig`の内部はspigotの`YamlConfiguration`を使用しているのでそちらの機能が使えます. )このクラスの初期値と等価な内容を表すYamlファイルを示しておきます. (`GzipConfig`はjavaのSerializeを利用しているのでファイルは読めません. )
``` yml
sample:
  num: 10
  text: hello!
```
Yamlファイルから設定を行う場合には`YamlConfig`を, 設定ファイルを圧縮してしまっておく場合には`GzipConfig`を使用します. 例を示します. 
``` java
Sample sample = new Sample();
YamlConfig yml = YamlConfig();
Serializer<Sample> serializer = new Serializer<>(yml);

// serialize
serializer.serialize(input, sample);

// deserialize
serializer.deserialize(file, sample);
```
`ConfigIO`を使えばより簡単に記述できます. 
```java
ConfigIO io = new ConfigIO();

// read
Sample sample = io.read(file, new Sample());

// write
io.write(file, sample);
```
